# Generated by Django 5.1.3 on 2025-02-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clusterning", "0001_initial"),
    ]

    operations = []
