# Generated by Django 5.1.3 on 2025-02-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusterning", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusteredText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField()),
                ("cluster_number", models.IntegerField()),
                ("processed_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Clustered Text",
                "verbose_name_plural": "Clustered Texts",
            },
        ),
        migrations.CreateModel(
            name="TextClusteringResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("num_clusters", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Text",
        ),
        migrations.AddField(
            model_name="clusteredtext",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="clusterning.textclusteringresult",
            ),
        ),
    ]
